version: '3.0'
services:
  binaries:
    build: testnet-binaries
    image: testnet-binaries
  node:
    build: node
    image: bnc-node
    depends_on:
      - binaries
    networks:
      - binance_rpc_net
    ports:
      - '26657:26657'
    volumes:
      - 'binance_data:/root/.bnbchaind/data'
  api-server:
    build: api-server
    image: bnc-api-server
    depends_on:
      - binaries
    networks:
      - binance_rpc_net
    ports:
      - '8080:8080'
    command: ["http://node:26657"]
networks:
  binance_rpc_net:
volumes:
  binance_data: